import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import Card from '../components/Card'
import Stack from '../components/Stack'
import { Card as CardType } from '../models'
import styles from '../styles/Home.module.css'

type Decks = {
  one: CardType[],
  two: CardType[],
  three: CardType[]
}

const Home: NextPage = () => {
  const [deck, setDeck] = useState<Decks>();

  // https://dev.to/codymjarrett/understanding-how-api-routes-work-in-next-js-50fm
  const init = async () => {
    const response = await fetch("/api/deck");
    if (!response.ok) {
      console.log(response.status);
      return;
    }
    const responseJson: Decks = await response.json();
    setDeck(responseJson);
  };

  useEffect(() => {
    init();
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Splendorific</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button className={styles.shuffle} onClick={() => init()}>Shuffle</button>

        <div className={styles.board}>
          {deck?.one.slice(0, 4)
            .map((card, i) => (
              <Card key={i} card={card} />
            ))
          }
          <Stack level={1} />

          {deck?.two.slice(0, 4)
            .map((card, i) => (
              <Card key={i} card={card} />
            ))
          }
          <Stack level={2} />

          {deck?.three.slice(0, 4)
            .map((card, i) => (
              <Card key={i} card={card} />
            ))
          }
          <Stack level={3} />
        </div>

        <div className={styles.bank}>
          <Image src="/images/chips.jpg" layout="fill" alt="" />
        </div>

      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export default Home
